### ISSUE TITLE
[Feature] Combat tracker

### ISSUE THREAD

**Issue by cryptism** [Cussa/fvtt-troika#2]
How's it going! This looks mega useful as I'm looking to transition to foundry ASAP.
Just playing with it initially, it would be nice to add a combat tracker akin to the fantastic Technical Grimoire offering so that can all be done in-house

I can make time to hack on this myself, but I'd be keen to know if you have some thoughts/headway into this yourself before I plunge in

**Comment by TheLastScrub** [comment]
Hey @cryptism, thanks for the compliments on the system. 

For initiative tracking, I just use a Roll Table, you can see the process I use on the main readme page. It isn't the most elegant, but it has worked fairly well for me. If you wanted to build something custom, or make something to automate the roll table process a bit though, feel free.

![image](https://user-images.githubusercontent.com/67403321/235334135-d6a743fe-c041-433e-93b1-6e4ac6fd86a2.png)

**Comment by cryptism** [comment]
Ah, totally neglected to see that sorry! I'll have a play with it and get some experience working with it first before I jump straight in with a proposal. Cheers.
