### ISSUE TITLE
v11 compatibility

### ISSUE THREAD

**Issue by monkey-bars** [Cussa/fvtt-troika#3]
Is the system going to be updated for v11? It doesn't seem to have any issue from my brief use of it, so maybe it just needs its tags updated?

**Comment by TheLastScrub** [comment]
It is on my to-do list to update it for v11. The main thing for it is to update the existing compendiums to the new database format, which would make it fully v11 compatible, although it also breaks backwards compatibility with v10. You are correct though, there are not any notable issues with using the system as it is with v11.

**Comment by TheLastScrub** [comment]
I just pushed a new update today, the changed in it are fairly minor. The biggest addition is that I included all the SRD (core rulebook) backgrounds in a compendium. But I've also bumped the core and minimum compatibility to v11, so it should not flag as a possible incompatibility anymore.
